.PHONY: all clean cleanall

all:
	$(MAKE) -C tinyPTC
	$(MAKE) -C picoPNG

clean:
	$(MAKE) -C tinyPTC clean
	$(MAKE) -C picoPNG clean

cleanall:
	$(MAKE) -C tinyPTC cleanall
	$(MAKE) -C picoPNG cleanall